run:
	@go run ./cmd/cmd.go 
install:
	@go build -o ./build/migrator ./cmd/cmd.go 
run-test:
	cd ./test && go test
lint:
	gocritic check ./...
	revive ./...
	golint ./...
	goconst ./...
	golangci-lint run
	go vet ./...
	staticcheck ./...
	